# Generated by Django 4.2.3 on 2023-07-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name of dynamic table column')),
                ('type', models.CharField(choices=[('BOOLEAN', 'boolean'), ('INTEGER', 'integer'), ('STRING', 'string')], default='STRING', max_length=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.dynamictable')),
            ],
        ),
    ]
