# Generated by Django 4.2.3 on 2023-07-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_dynamictablerow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DynamicTableRow',
            new_name='DynamicTableColumn',
        ),
    ]
